# Generated by Django 4.2.3 on 2023-10-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.description'),
        ),
    ]
