# Generated by Django 4.2.3 on 2023-10-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='image',
            field=models.TextField(max_length=256),
        ),
    ]
