# Generated by Django 4.2.3 on 2023-12-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_image_image'),
        ('inventory', '0015_alter_subproduct_image'),
    ]

    operations = [
    ]
